name: Environmental Studies
type: major
degree: Bachelor of Arts
catalog: 2018-19

result:
  count: all
  of:
    - Major
    - Areas of Emphasis

requirements:
  Major:
    result:
      count: all
      of: [ENVST 137, ENVST 237, ENVST 399]

  Areas of Emphasis:
    result:
      count: any
      of:
        - requirement: Natural Science
        - requirement: Social Science
        - requirement: Arts and Humanities

    requirements:
      Natural Science:
        result:
          count: all
          of:
            - requirement: Social Sciences for Natural Science
            - requirement: Arts and Humanities for Natural Science
            - requirement: Statistics, Modeling, and Mapping
            - requirement: Intermediate Chemistry
            - requirement: Intermediate Ecology
            - requirement: Environmental Science

            - given: these requirements
              requirements:
                - requirement: Social Sciences for Natural Science
                - requirement: Arts and Humanities for Natural Science
                - requirement: Statistics, Modeling, and Mapping
                - requirement: Intermediate Chemistry
                - requirement: Intermediate Ecology
                - requirement: Environmental Science
              what: courses
              do: count >= 9

        requirements:
          Social Sciences for Natural Science:
            result:
              count: 1
              of:
                - ES/PS 201
                - ENVST 232
                - ENVST 235
                - ES/PS 276
                - AS/ES 277
                - { course: ENVST 281, term: 2014-5 }
                - ENVST 381
                - ECON 242
                - ID 234
                - PSCI 221
                - PSYCH 227
                - SOAN 222
                - SOAN 247
                - { course: SOAN 297, term: 2015-3 }

          Arts and Humanities for Natural Science:
            result:
              count: 1
              of:
                - ENVST 202
                - either: [PHIL 257, REL 278]

          Statistics, Modeling, and Mapping:
            result:
              count: 1
              of: [ENVST 255, STAT 212, STAT 272]

          Intermediate Chemistry:
            result:
              count: 1
              of:
                - both: [CHEM 248, CHEM 254]
                - both: [CHEM 255, CHEM 256]

          Intermediate Ecology:
            result:
              count: 1
              of: [BIO 261, BIO 226]

          Environmental Science:
            result:
              given: these courses
              courses:
                - ENVST 123
                - BI/ES 226
                - BI/ES 228
                - ENVST 245
                - ENVST 255
                - { course: ENVST 281, term: 2000-1 }
                - BI/ES 286
                - BI/ES 250
                - { course: ENVST 381, term: 2000-1 }
                - ENVST 397
                - BIO 224
                - BI/ES 350
                - BIO 371
                - { course: BIO 391, term: 2000-1 }
                - { course: CHEM 391, term: 2000-1 }
                - { course: ENVST 391, term: 2000-1 }
              repeats: first
              limit:
                - where: { department: "! ENVST", level: "200" }
                  at_most: 1
                - where: { level: "! 300" }
                  at_most: 2
              what: courses
              do: count >= 3

      Social Science:
        result:
          count: all
          of:
            - requirement: Natural Science for Social Sciences
            - requirement: Arts and Humanities for Social Sciences
            - requirement: Methodological Analysis
            - requirement: Economic Analysis
            - requirement: Environmental Political Policy and Institutions
            - requirement: Social Science Electives

            - given: these requirements
              requirements:
                - requirement: Natural Science for Social Sciences
                - requirement: Arts and Humanities for Social Sciences
                - requirement: Methodological Analysis
                - requirement: Economic Analysis
                - requirement: Environmental Political Policy and Institutions
                - requirement: Social Science Electives
              what: courses
              do: count >= 9

        requirements:
          Natural Science for Social Sciences:
            result:
              count: 1
              of:
                - ENVST 123
                - ENVST 245
                - ENVST 255
                - { course: ENVST 281, term: 2000-1 }
                - { course: ENVST 381, term: 2000-1 }
                - BI/ES 226
                - BI/ES 228
                - BI/ES 286
                - BI/ES 350
                - BIO 224
                - either: [BIO 226, BIO 261]
                - CHEM 124
                - both: [CHEM 225, CHEM 256]
                - { course: BIO 391, term: 2000-1 }
                - { course: CHEM 391, term: 2000-1 }

          Arts and Humanities for Social Sciences:
            result:
              count: 1
              of:
                - ENVST 202
                - ENVST 270
                - { course: ENVST 281, term: 2000-1 }
                - { course: ENVST 381, term: 2000-1 }
                - FILM 230
                - GERM 276
                - HIST 245
                - HIST 275
                - { course: NORW 224, term: 2000-1 }
                - either: [PHIL 257, REL 278]
                - ENGL 276

          Methodological Analysis:
            result:
              count: 1
              of:
                - ENVST 255
                - STAT 110
                - STAT 212
                - STAT 214
                - STAT 272
                - ECON 263
                - SOAN 371
                - PSYCH 230
                - PSCI 220

          Economic Analysis:
            message: The department strongly recommends taking ECON 121
            result:
              count: all
              of:
                - count: any
                  of:
                    - ECON 121
                    - ECON 110
                    - ECON 111
                    - ECON 112
                    - ECON 113
                    - ECON 114
                    - ECON 115
                    - ECON 116
                    - ECON 117
                    - ECON 118
                    - ECON 119
                    - ECON 120
                - ECON 242

          Environmental Political Policy and Institutions:
            result:
              count: 1
              of: [ENVST 232, ES/PS 201, ES/PS 276]

          Social Science Electives:
            result:
              count: 2
              of:
                - ES/PS 201
                - ENVST 232
                - ENVST 235
                - ES/PS 276
                - { course: ENVST 281, term: 2000-1 }
                - { course: ENVST 381, term: 2000-1 }
                - { course: ENVST 396, term: 2000-1 }
                - ECON 243
                - PSYCH 227
                - SOAN 247
                - { course: SOAN 297, term: 2000-1 }
                - PSCI 221
                - SOAN 222
                - ID 234
                - AS/ES 227

      Arts and Humanities:
        result:
          count: all
          of:
            - requirement: Natural Science for Social Sciences
            - requirement: Arts and Humanities for Social Sciences
            - requirement: Methodological Analysis
            - requirement: Economic Analysis
            - requirement: Environmental Political Policy and Institutions
            - requirement: Social Science Electives

            - given: these requirements
              requirements:
                - requirement: Natural Science for Social Sciences
                - requirement: Arts and Humanities for Social Sciences
                - requirement: Methodological Analysis
                - requirement: Economic Analysis
                - requirement: Environmental Political Policy and Institutions
                - requirement: Social Science Electives
              what: courses
              do: count >= 9

        requirements:
          Natural Science for Arts and the Humanities:
            result:
              count: 1
              of:
                - ENVST 123
                - ENVST 245
                - ENVST 255
                - { course: ENVST 281, term: 2000-1 }
                - { course: ENVST 381, term: 2000-1 }
                - BI/ES 226
                - BI/ES 228
                - BI/ES 286
                - BI/ES 350
                - BIO 224
                - either: [BIO 226, BIO 261]
                - CHEM 124
                - both: [CHEM 225, CHEM 256]
                - { course: BIO 391, term: 2000-1 }
                - { course: CHEM 391, term: 2000-1 }

          Social Sciences for Arts and the Humanities:
            result:
              count: 1
              of:
                - ENVST 232
                - ENVST 235
                - { course: ENVST 281, term: 2000-1 }
                - { course: ENVST 381, term: 2000-1 }
                - ES/PS 201
                - ES/PS 276
                - ECON 242
                - PSCI 221
                - PSYCH 227
                - SOAN 222
                - SOAN 247
                - AS/ES 277

          Courses for Arts and the Humanities:
            result:
              given: these courses
              courses:
                - ENVST 202
                - ENVST 270
                - { course: ENVST 281, term: 2000-1 }
                - { course: ENVST 381, term: 2000-1 }
                - FILM 230
                - GERM 276
                - HIST 245
                - HIST 275
                - { course: NORW 224, term: 2000-1 }
                - PHIL 257
                - ENGL 276
                - REL 278
                - ENVST 381
                - { course: DEPT 301, term: 2000-1 }
              repeats: first
              limit:
                - { at_most: 5, where: { level: "200" } }
              what: courses
              do: count >= 6
